### ISSUE TITLE
WJC West Routing Issue

### ISSUE THREAD

**Issue by David-Yarnell** [USEPA/arcgis-indoors#131]
From Harvey: Routing should not be going to the elevator and down a floor.
![WJC_West_RoutingIssue_1](https://user-images.githubusercontent.com/5278901/186008338-b3c9fbf3-88f5-45bc-90c7-0c45673cb03e.png)

**Comment by David-Yarnell** [comment]
Here is another:
![IndoorsViewer_RoutingIssue_2](https://user-images.githubusercontent.com/5278901/186010006-6e4ccd7d-8f1e-42ae-8192-a31e81ba76ce.png)

This one works correctly between two floors.
![IndoorsViewer_RoutingIssue_3](https://user-images.githubusercontent.com/5278901/186010018-4d024d82-7225-4d43-a05e-e331d6ed5ab4.png)

**Comment by David-Yarnell** [comment]
@bbradshawInnovate can you test the example above with a network created from pathways and transitions with the domains? I attempted this and I still got incorrect directions from the first example in this thread.

**Comment by bbradshawInnovate** [comment]
@David-Yarnell yeah ill check it out

**Comment by bbradshawInnovate** [comment]
@David-Yarnell Here is what I got when I ran it. Though the method used to get to the final destination is different it still is correct.

![2022-10-17_10-28-51](https://user-images.githubusercontent.com/62765653/196243951-5128e069-5ce6-4989-b683-4a12ce08491b.jpg)

**Comment by bbradshawInnovate** [comment]
@David-Yarnell Tested the first screenshot and with my network updates it successfully routes correctly 
![image](https://user-images.githubusercontent.com/62765653/196248085-9a446cb7-e0c3-4089-8bcb-867a49b76af5.png)

**Comment by David-Yarnell** [comment]
@bbradshawInnovate that is great! Thank you!

**Comment by David-Yarnell** [comment]
It issue was resolved by publishing the network from the file gdb. Will need further investigation to identify how to get the network to publish correctly from other type of dbs. See [issue #134](https://github.com/USEPA/arcgis-indoors/issues/134)
