### ISSUE TITLE
WJC - CW Updated Basement Data

### ISSUE THREAD

**Issue by David-Yarnell** [USEPA/arcgis-indoors#132]

**Comment by arichards-innovate** [comment]
In the bottom right of this image is an electrical room. There does not appear to be any sort way into it. The Upper Electrical Room above it looks like a large, tall room with stairs up to a mezzanine which leads to the rest of the building. Additionally, this Upper Electrical Room looks to have a ladder with a safety hoop around it leading to the Stage Electrical Room in question. Tough to explain the 3D space but I believe this room is only accessed via ladder though we're not sure how to list a ladder on here. I believe a door is the simplest way though stairs can work as well. @bbradshawInnovate 

![image](https://user-images.githubusercontent.com/100383195/194350158-215cf6b5-cbe6-427d-94f8-20f81f36d7a6.png)

**Comment by bbradshawInnovate** [comment]
@arichards-innovate You don't necessarily need to list it as a door. I would just path the network through manually. My guess is going forward EPA will probably want us to restrict access to these areas.

**Comment by jlherring** [comment]
@michaelblair test
