### ISSUE TITLE
POCH Building R1

### ISSUE THREAD

**Issue by bbradshawInnovate** [USEPA/arcgis-indoors#49]

**Comment by nmcdonald-innovate** [comment]
[QuestionsInR1Building.docx](https://github.com/USEPA/arcgis-indoors/files/9767753/QuestionsInR1Building.docx)
@jlherring @David-Yarnell I have attached questions about some staircases in the R1 building I'd like to verify with EPA before handing off to Bryce to rebuild the network. Thanks!

**Comment by nmcdonald-innovate** [comment]
![GIS Changes to R1](https://user-images.githubusercontent.com/100317674/197887772-eb6a3a11-fcd4-484a-9f3e-342481ab38f8.PNG)
@David-Yarnell There have been renovations to a couple of the office spaces on Floor 5 and Floor 7 I have taken screenshots and notes of. What they look like post renovation is in red. In the interest of time, Jenny and I thought it's likely best to proceed with processing R1 as is for now and worry about changing the blueprint of the building at a future date in time.

**Comment by bbradshawInnovate** [comment]
Need further clarification on where these stairs end up. Though they start on floor 1 when you go to floor 2 there are no stairs present. 
![image](https://user-images.githubusercontent.com/62765653/198708562-e9726a58-7dbe-4681-b81e-5efc3cb8cde4.png)
