### ISSUE TITLE
WJC - CW

### ISSUE THREAD

**Issue by bbradshawInnovate** [USEPA/arcgis-indoors#73]

**Comment by bbradshawInnovate** [comment]
#32
#33 
#25 
#26 
#27 
#28 
#29 
#30 
#31

**Comment by arichards-innovate** [comment]
Double check the mezzanine process. How do we put it in there? Is it part of two buildings? how is that handled? does it need to be included at all?

**Comment by bbradshawInnovate** [comment]
@arichards-innovate let's go over this on Monday

**Comment by arichards-innovate** [comment]
Having issues thinning indoor pathways. It gets through the 7 floors then says the following

"ERROR 180212: Unable to thin input pathways.
ERROR 000539: Invalid field PrelimTransitions.LEVEL_ID
Failed to execute (CalculateField)."

It makes it through all 7 floors before attempting to join back attributes (I think, it might complete that and fail on whatever follows but not positive". Its especially strange as there is no PrelimTransitions.LEVEL_ID.

**Comment by arichards-innovate** [comment]
Having issues thinning pathways. Sent to Bryce for further assistance. Thin pathways tool is asking for a LevelID in prelimtransitions, which the new schema does not contain LevelID in it.
